//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Employee.
    /// </summary>
    // *** Start programmer edit section *** (Employee CustomAttributes)

    // *** End programmer edit section *** (Employee CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployeeE", new string[] {
            "FirstName as \'First name\'",
            "LastName as \'Last name\'",
            "MiddleName as \'Middle name\'",
            "Sex as \'Sex\'"})]
    [View("EmployeeL", new string[] {
            "FirstName as \'First name\'",
            "LastName as \'Last name\'",
            "MiddleName as \'Middle name\'",
            "Sex as \'Sex\'"})]
    public class Employee : ICSSoft.STORMNET.DataObject
    {
        
        private string fFirstName;
        
        private string fMiddleName;
        
        private string fLastName;
        
        private IIS.Hotel.Sex fSex;
        
        // *** Start programmer edit section *** (Employee CustomMembers)

        // *** End programmer edit section *** (Employee CustomMembers)

        
        /// <summary>
        /// FirstName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.FirstName CustomAttributes)

        // *** End programmer edit section *** (Employee.FirstName CustomAttributes)
        [StrLen(255)]
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.FirstName Get start)

                // *** End programmer edit section *** (Employee.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Employee.FirstName Get end)

                // *** End programmer edit section *** (Employee.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.FirstName Set start)

                // *** End programmer edit section *** (Employee.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Employee.FirstName Set end)

                // *** End programmer edit section *** (Employee.FirstName Set end)
            }
        }
        
        /// <summary>
        /// MiddleName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.MiddleName CustomAttributes)

        // *** End programmer edit section *** (Employee.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.MiddleName Get start)

                // *** End programmer edit section *** (Employee.MiddleName Get start)
                string result = this.fMiddleName;
                // *** Start programmer edit section *** (Employee.MiddleName Get end)

                // *** End programmer edit section *** (Employee.MiddleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.MiddleName Set start)

                // *** End programmer edit section *** (Employee.MiddleName Set start)
                this.fMiddleName = value;
                // *** Start programmer edit section *** (Employee.MiddleName Set end)

                // *** End programmer edit section *** (Employee.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// LastName.
        /// </summary>
        // *** Start programmer edit section *** (Employee.LastName CustomAttributes)

        // *** End programmer edit section *** (Employee.LastName CustomAttributes)
        [StrLen(255)]
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Employee.LastName Get start)

                // *** End programmer edit section *** (Employee.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Employee.LastName Get end)

                // *** End programmer edit section *** (Employee.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.LastName Set start)

                // *** End programmer edit section *** (Employee.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Employee.LastName Set end)

                // *** End programmer edit section *** (Employee.LastName Set end)
            }
        }
        
        /// <summary>
        /// Sex.
        /// </summary>
        // *** Start programmer edit section *** (Employee.Sex CustomAttributes)

        // *** End programmer edit section *** (Employee.Sex CustomAttributes)
        public virtual IIS.Hotel.Sex Sex
        {
            get
            {
                // *** Start programmer edit section *** (Employee.Sex Get start)

                // *** End programmer edit section *** (Employee.Sex Get start)
                IIS.Hotel.Sex result = this.fSex;
                // *** Start programmer edit section *** (Employee.Sex Get end)

                // *** End programmer edit section *** (Employee.Sex Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.Sex Set start)

                // *** End programmer edit section *** (Employee.Sex Set start)
                this.fSex = value;
                // *** Start programmer edit section *** (Employee.Sex Set end)

                // *** End programmer edit section *** (Employee.Sex Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeE", typeof(IIS.Hotel.Employee));
                }
            }
            
            /// <summary>
            /// "EmployeeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeL", typeof(IIS.Hotel.Employee));
                }
            }
        }
    }
}
