//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hotel.
    /// </summary>
    // *** Start programmer edit section *** (Hotel CustomAttributes)

    // *** End programmer edit section *** (Hotel CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HotelE", new string[] {
            "Name as \'Name\'",
            "Address as \'Address\'",
            "Manager as \'Manager\'",
            "Manager.FirstName as \'First name\'"}, Hidden=new string[] {
            "Manager.FirstName"})]
    [AssociatedDetailViewAttribute("HotelE", "Rooms", "RoomE", true, "", "Rooms", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("HotelE", "Employees", "HotelEmployeeE", true, "", "Employees", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("HotelE", "Manager", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FirstName")]
    [View("HotelL", new string[] {
            "Name as \'Name\'",
            "Address as \'Address\'",
            "Manager.FirstName as \'First name\'"})]
    public class Hotel : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fAddress;
        
        private IIS.Hotel.Employee fManager;
        
        private IIS.Hotel.DetailArrayOfHotelEmployee fEmployees;
        
        private IIS.Hotel.DetailArrayOfRoom fRooms;
        
        // *** Start programmer edit section *** (Hotel CustomMembers)

        // *** End programmer edit section *** (Hotel CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Hotel.Name CustomAttributes)

        // *** End programmer edit section *** (Hotel.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Hotel.Name Get start)

                // *** End programmer edit section *** (Hotel.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Hotel.Name Get end)

                // *** End programmer edit section *** (Hotel.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hotel.Name Set start)

                // *** End programmer edit section *** (Hotel.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Hotel.Name Set end)

                // *** End programmer edit section *** (Hotel.Name Set end)
            }
        }
        
        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (Hotel.Address CustomAttributes)

        // *** End programmer edit section *** (Hotel.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Hotel.Address Get start)

                // *** End programmer edit section *** (Hotel.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Hotel.Address Get end)

                // *** End programmer edit section *** (Hotel.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hotel.Address Set start)

                // *** End programmer edit section *** (Hotel.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Hotel.Address Set end)

                // *** End programmer edit section *** (Hotel.Address Set end)
            }
        }
        
        /// <summary>
        /// Hotel.
        /// </summary>
        // *** Start programmer edit section *** (Hotel.Manager CustomAttributes)

        // *** End programmer edit section *** (Hotel.Manager CustomAttributes)
        public virtual IIS.Hotel.Employee Manager
        {
            get
            {
                // *** Start programmer edit section *** (Hotel.Manager Get start)

                // *** End programmer edit section *** (Hotel.Manager Get start)
                IIS.Hotel.Employee result = this.fManager;
                // *** Start programmer edit section *** (Hotel.Manager Get end)

                // *** End programmer edit section *** (Hotel.Manager Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hotel.Manager Set start)

                // *** End programmer edit section *** (Hotel.Manager Set start)
                this.fManager = value;
                // *** Start programmer edit section *** (Hotel.Manager Set end)

                // *** End programmer edit section *** (Hotel.Manager Set end)
            }
        }
        
        /// <summary>
        /// Hotel.
        /// </summary>
        // *** Start programmer edit section *** (Hotel.Employees CustomAttributes)

        // *** End programmer edit section *** (Hotel.Employees CustomAttributes)
        public virtual IIS.Hotel.DetailArrayOfHotelEmployee Employees
        {
            get
            {
                // *** Start programmer edit section *** (Hotel.Employees Get start)

                // *** End programmer edit section *** (Hotel.Employees Get start)
                if ((this.fEmployees == null))
                {
                    this.fEmployees = new IIS.Hotel.DetailArrayOfHotelEmployee(this);
                }
                IIS.Hotel.DetailArrayOfHotelEmployee result = this.fEmployees;
                // *** Start programmer edit section *** (Hotel.Employees Get end)

                // *** End programmer edit section *** (Hotel.Employees Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hotel.Employees Set start)

                // *** End programmer edit section *** (Hotel.Employees Set start)
                this.fEmployees = value;
                // *** Start programmer edit section *** (Hotel.Employees Set end)

                // *** End programmer edit section *** (Hotel.Employees Set end)
            }
        }
        
        /// <summary>
        /// Hotel.
        /// </summary>
        // *** Start programmer edit section *** (Hotel.Rooms CustomAttributes)

        // *** End programmer edit section *** (Hotel.Rooms CustomAttributes)
        public virtual IIS.Hotel.DetailArrayOfRoom Rooms
        {
            get
            {
                // *** Start programmer edit section *** (Hotel.Rooms Get start)

                // *** End programmer edit section *** (Hotel.Rooms Get start)
                if ((this.fRooms == null))
                {
                    this.fRooms = new IIS.Hotel.DetailArrayOfRoom(this);
                }
                IIS.Hotel.DetailArrayOfRoom result = this.fRooms;
                // *** Start programmer edit section *** (Hotel.Rooms Get end)

                // *** End programmer edit section *** (Hotel.Rooms Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hotel.Rooms Set start)

                // *** End programmer edit section *** (Hotel.Rooms Set start)
                this.fRooms = value;
                // *** Start programmer edit section *** (Hotel.Rooms Set end)

                // *** End programmer edit section *** (Hotel.Rooms Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HotelE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HotelE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HotelE", typeof(IIS.Hotel.Hotel));
                }
            }
            
            /// <summary>
            /// "HotelL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HotelL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HotelL", typeof(IIS.Hotel.Hotel));
                }
            }
        }
    }
}
