//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hotel employee.
    /// </summary>
    // *** Start programmer edit section *** (HotelEmployee CustomAttributes)

    // *** End programmer edit section *** (HotelEmployee CustomAttributes)
    [AutoAltered()]
    [Caption("Hotel employee")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HotelEmployeeE", new string[] {
            "StartWorkDate as \'Start work date\'",
            "EndWorkDate as \'End work date\'",
            "Employee as \'Employee\'",
            "Employee.FirstName as \'First name\'"}, Hidden=new string[] {
            "Employee.FirstName"})]
    [MasterViewDefineAttribute("HotelEmployeeE", "Employee", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FirstName")]
    public class HotelEmployee : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStartWorkDate;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fEndWorkDate;
        
        private IIS.Hotel.Employee fEmployee;
        
        private IIS.Hotel.Hotel fHotel;
        
        // *** Start programmer edit section *** (HotelEmployee CustomMembers)

        // *** End programmer edit section *** (HotelEmployee CustomMembers)

        
        /// <summary>
        /// StartWorkDate.
        /// </summary>
        // *** Start programmer edit section *** (HotelEmployee.StartWorkDate CustomAttributes)

        // *** End programmer edit section *** (HotelEmployee.StartWorkDate CustomAttributes)
        public virtual System.DateTime StartWorkDate
        {
            get
            {
                // *** Start programmer edit section *** (HotelEmployee.StartWorkDate Get start)

                // *** End programmer edit section *** (HotelEmployee.StartWorkDate Get start)
                System.DateTime result = this.fStartWorkDate;
                // *** Start programmer edit section *** (HotelEmployee.StartWorkDate Get end)

                // *** End programmer edit section *** (HotelEmployee.StartWorkDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HotelEmployee.StartWorkDate Set start)

                // *** End programmer edit section *** (HotelEmployee.StartWorkDate Set start)
                this.fStartWorkDate = value;
                // *** Start programmer edit section *** (HotelEmployee.StartWorkDate Set end)

                // *** End programmer edit section *** (HotelEmployee.StartWorkDate Set end)
            }
        }
        
        /// <summary>
        /// EndWorkDate.
        /// </summary>
        // *** Start programmer edit section *** (HotelEmployee.EndWorkDate CustomAttributes)

        // *** End programmer edit section *** (HotelEmployee.EndWorkDate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime EndWorkDate
        {
            get
            {
                // *** Start programmer edit section *** (HotelEmployee.EndWorkDate Get start)

                // *** End programmer edit section *** (HotelEmployee.EndWorkDate Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fEndWorkDate;
                // *** Start programmer edit section *** (HotelEmployee.EndWorkDate Get end)

                // *** End programmer edit section *** (HotelEmployee.EndWorkDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HotelEmployee.EndWorkDate Set start)

                // *** End programmer edit section *** (HotelEmployee.EndWorkDate Set start)
                this.fEndWorkDate = value;
                // *** Start programmer edit section *** (HotelEmployee.EndWorkDate Set end)

                // *** End programmer edit section *** (HotelEmployee.EndWorkDate Set end)
            }
        }
        
        /// <summary>
        /// Hotel employee.
        /// </summary>
        // *** Start programmer edit section *** (HotelEmployee.Employee CustomAttributes)

        // *** End programmer edit section *** (HotelEmployee.Employee CustomAttributes)
        [NotNull()]
        public virtual IIS.Hotel.Employee Employee
        {
            get
            {
                // *** Start programmer edit section *** (HotelEmployee.Employee Get start)

                // *** End programmer edit section *** (HotelEmployee.Employee Get start)
                IIS.Hotel.Employee result = this.fEmployee;
                // *** Start programmer edit section *** (HotelEmployee.Employee Get end)

                // *** End programmer edit section *** (HotelEmployee.Employee Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HotelEmployee.Employee Set start)

                // *** End programmer edit section *** (HotelEmployee.Employee Set start)
                this.fEmployee = value;
                // *** Start programmer edit section *** (HotelEmployee.Employee Set end)

                // *** End programmer edit section *** (HotelEmployee.Employee Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Hotel.Hotel.
        /// </summary>
        // *** Start programmer edit section *** (HotelEmployee.Hotel CustomAttributes)

        // *** End programmer edit section *** (HotelEmployee.Hotel CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Hotel.Hotel Hotel
        {
            get
            {
                // *** Start programmer edit section *** (HotelEmployee.Hotel Get start)

                // *** End programmer edit section *** (HotelEmployee.Hotel Get start)
                IIS.Hotel.Hotel result = this.fHotel;
                // *** Start programmer edit section *** (HotelEmployee.Hotel Get end)

                // *** End programmer edit section *** (HotelEmployee.Hotel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (HotelEmployee.Hotel Set start)

                // *** End programmer edit section *** (HotelEmployee.Hotel Set start)
                this.fHotel = value;
                // *** Start programmer edit section *** (HotelEmployee.Hotel Set end)

                // *** End programmer edit section *** (HotelEmployee.Hotel Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HotelEmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HotelEmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HotelEmployeeE", typeof(IIS.Hotel.HotelEmployee));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of HotelEmployee.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfHotelEmployee CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfHotelEmployee CustomAttributes)
    public class DetailArrayOfHotelEmployee : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Hotel.DetailArrayOfHotelEmployee members)

        // *** End programmer edit section *** (IIS.Hotel.DetailArrayOfHotelEmployee members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type HotelEmployee by index.
        /// </summary>
        /// <summary>
        /// Adds object with type HotelEmployee.
        /// </summary>
        public DetailArrayOfHotelEmployee(IIS.Hotel.Hotel fHotel) : 
                base(typeof(HotelEmployee), ((ICSSoft.STORMNET.DataObject)(fHotel)))
        {
        }
        
        public IIS.Hotel.HotelEmployee this[int index]
        {
            get
            {
                return ((IIS.Hotel.HotelEmployee)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Hotel.HotelEmployee dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
