//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RoomE", new string[] {
            "Number as \'Number\'"})]
    [View("RoomL", new string[] {
            "Number as \'Номер\'",
            "Hotel.Name as \'Отель\'"})]
    public class Room : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber;
        
        private IIS.Hotel.Hotel fHotel;
        
        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Room.Number CustomAttributes)

        // *** End programmer edit section *** (Room.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Room.Number Get start)

                // *** End programmer edit section *** (Room.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Room.Number Get end)

                // *** End programmer edit section *** (Room.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Number Set start)

                // *** End programmer edit section *** (Room.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Room.Number Set end)

                // *** End programmer edit section *** (Room.Number Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Hotel.Hotel.
        /// </summary>
        // *** Start programmer edit section *** (Room.Hotel CustomAttributes)

        // *** End programmer edit section *** (Room.Hotel CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Hotel.Hotel Hotel
        {
            get
            {
                // *** Start programmer edit section *** (Room.Hotel Get start)

                // *** End programmer edit section *** (Room.Hotel Get start)
                IIS.Hotel.Hotel result = this.fHotel;
                // *** Start programmer edit section *** (Room.Hotel Get end)

                // *** End programmer edit section *** (Room.Hotel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Hotel Set start)

                // *** End programmer edit section *** (Room.Hotel Set start)
                this.fHotel = value;
                // *** Start programmer edit section *** (Room.Hotel Set end)

                // *** End programmer edit section *** (Room.Hotel Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomE", typeof(IIS.Hotel.Room));
                }
            }
            
            /// <summary>
            /// "RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomL", typeof(IIS.Hotel.Room));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Room.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfRoom CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfRoom CustomAttributes)
    public class DetailArrayOfRoom : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Hotel.DetailArrayOfRoom members)

        // *** End programmer edit section *** (IIS.Hotel.DetailArrayOfRoom members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Room by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Room.
        /// </summary>
        public DetailArrayOfRoom(IIS.Hotel.Hotel fHotel) : 
                base(typeof(Room), ((ICSSoft.STORMNET.DataObject)(fHotel)))
        {
        }
        
        public IIS.Hotel.Room this[int index]
        {
            get
            {
                return ((IIS.Hotel.Room)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Hotel.Room dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
