//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Visit.
    /// </summary>
    // *** Start programmer edit section *** (Visit CustomAttributes)

    // *** End programmer edit section *** (Visit CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("VisitE", new string[] {
            "StartVisitDate as \'Start visit date\'",
            "EndVisitdate as \'End visitdate\'",
            "Person as \'Person\'",
            "Person.FullName as \'Full name\'",
            "Room as \'Room\'",
            "Room.Number as \'Number\'"}, Hidden=new string[] {
            "Person.FullName",
            "Room.Number"})]
    [MasterViewDefineAttribute("VisitE", "Person", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FullName")]
    [MasterViewDefineAttribute("VisitE", "Room", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Number")]
    [View("VisitL", new string[] {
            "StartVisitDate as \'Start visit date\'",
            "EndVisitdate as \'End visitdate\'",
            "Person.FullName as \'Full name\'",
            "Room.Number as \'Number\'"})]
    public class Visit : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStartVisitDate;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fEndVisitdate;
        
        private IIS.Hotel.Person fPerson;
        
        private IIS.Hotel.Room fRoom;
        
        // *** Start programmer edit section *** (Visit CustomMembers)

        // *** End programmer edit section *** (Visit CustomMembers)

        
        /// <summary>
        /// StartVisitDate.
        /// </summary>
        // *** Start programmer edit section *** (Visit.StartVisitDate CustomAttributes)

        // *** End programmer edit section *** (Visit.StartVisitDate CustomAttributes)
        public virtual System.DateTime StartVisitDate
        {
            get
            {
                // *** Start programmer edit section *** (Visit.StartVisitDate Get start)

                // *** End programmer edit section *** (Visit.StartVisitDate Get start)
                System.DateTime result = this.fStartVisitDate;
                // *** Start programmer edit section *** (Visit.StartVisitDate Get end)

                // *** End programmer edit section *** (Visit.StartVisitDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Visit.StartVisitDate Set start)

                // *** End programmer edit section *** (Visit.StartVisitDate Set start)
                this.fStartVisitDate = value;
                // *** Start programmer edit section *** (Visit.StartVisitDate Set end)

                // *** End programmer edit section *** (Visit.StartVisitDate Set end)
            }
        }
        
        /// <summary>
        /// EndVisitdate.
        /// </summary>
        // *** Start programmer edit section *** (Visit.EndVisitdate CustomAttributes)

        // *** End programmer edit section *** (Visit.EndVisitdate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime EndVisitdate
        {
            get
            {
                // *** Start programmer edit section *** (Visit.EndVisitdate Get start)

                // *** End programmer edit section *** (Visit.EndVisitdate Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fEndVisitdate;
                // *** Start programmer edit section *** (Visit.EndVisitdate Get end)

                // *** End programmer edit section *** (Visit.EndVisitdate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Visit.EndVisitdate Set start)

                // *** End programmer edit section *** (Visit.EndVisitdate Set start)
                this.fEndVisitdate = value;
                // *** Start programmer edit section *** (Visit.EndVisitdate Set end)

                // *** End programmer edit section *** (Visit.EndVisitdate Set end)
            }
        }
        
        /// <summary>
        /// Visit.
        /// </summary>
        // *** Start programmer edit section *** (Visit.Person CustomAttributes)

        // *** End programmer edit section *** (Visit.Person CustomAttributes)
        [NotNull()]
        public virtual IIS.Hotel.Person Person
        {
            get
            {
                // *** Start programmer edit section *** (Visit.Person Get start)

                // *** End programmer edit section *** (Visit.Person Get start)
                IIS.Hotel.Person result = this.fPerson;
                // *** Start programmer edit section *** (Visit.Person Get end)

                // *** End programmer edit section *** (Visit.Person Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Visit.Person Set start)

                // *** End programmer edit section *** (Visit.Person Set start)
                this.fPerson = value;
                // *** Start programmer edit section *** (Visit.Person Set end)

                // *** End programmer edit section *** (Visit.Person Set end)
            }
        }
        
        /// <summary>
        /// Visit.
        /// </summary>
        // *** Start programmer edit section *** (Visit.Room CustomAttributes)

        // *** End programmer edit section *** (Visit.Room CustomAttributes)
        [NotNull()]
        public virtual IIS.Hotel.Room Room
        {
            get
            {
                // *** Start programmer edit section *** (Visit.Room Get start)

                // *** End programmer edit section *** (Visit.Room Get start)
                IIS.Hotel.Room result = this.fRoom;
                // *** Start programmer edit section *** (Visit.Room Get end)

                // *** End programmer edit section *** (Visit.Room Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Visit.Room Set start)

                // *** End programmer edit section *** (Visit.Room Set start)
                this.fRoom = value;
                // *** Start programmer edit section *** (Visit.Room Set end)

                // *** End programmer edit section *** (Visit.Room Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "VisitE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VisitE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VisitE", typeof(IIS.Hotel.Visit));
                }
            }
            
            /// <summary>
            /// "VisitL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VisitL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VisitL", typeof(IIS.Hotel.Visit));
                }
            }
        }
    }
}
